### ISSUE TITLE
Cannot import Dot

### ISSUE THREAD

**Issue by alexprengere** [log0/pydot3#1]
I switched from `pydot2` to `pydot3` and I got this error:

``` python
>>> import pydot
>>> pydot.Dot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Dot'
```

I am using the latest version from PyPI, but I reproduced the bug from the github repo too.

**Comment by electrocucaracha** [comment]
Same here.  Even installing from source code I'm getting the same.
